# -*- coding: utf-8 -*-
"""Data_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUWurPPbWGCcyT6fLe4KFBMEuVhG-lQz
"""

from keras.models import Sequential
import pandas as pd
from keras.layers import Dense, Conv1D, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
import numpy as np

# from google.colab import files
# uploaded = files.upload()

data=pd.read_csv("customer_shopping_behavior.csv",delimiter=",")
#data=np.asarray(data)
print (data)
#data=np.asarray(data)
#print (data)
# x=data[:,:-1]
# x=np.asfarray(x,float)
# y=data[:,-1]
# y=np.asfarray(y,float)

#print(x.shape)
#print(data)
#print(x)
#print(y)

data.describe(include='all')

data.isnull().sum()

"""Fill the nulkl values with median."""

data['Review Rating'] = (
    data.groupby('Category')['Review Rating']
        .transform(lambda x: x.fillna(x.median()))
)

data.isnull().sum()

"""Data Pre-processing"""

data.columns = (
    data.columns
        .str.lower()
        .str.replace(' ', '_')
)

data.isnull().sum()

"""Data Cleaning"""

data.columns = (
    data.columns
        .str.lower()
        .str.replace(r'[^\w]', '_', regex=True)
        .str.replace(r'_+', '_', regex=True)
        .str.strip('_')
)

# @title
data.columns

"""Sampling Generations"""

labels = ['Young', 'Adult', 'Middle-Aged', 'Senior']

data['age_group'] = pd.qcut(
    data['age'],
    q=4,
    labels=labels
)

data.columns

frequency_mapping={
    'Fortinightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90,
}
data['frequency_of_purchases']=data['frequency_of_purchases'].map(frequency_mapping)

data[['discount_applied', 'promo_code_used']]

(data['discount_applied'] == data['promo_code_used']).all()

"""Removing Duplicate Data, For each discount it must have promo code."""

data=data.drop('promo_code_used',axis=1)

"""Setup Post Gre Sql and connection

"""

#!pip install psycopg2-binary sqlalchemy
!pip -q install sqlalchemy psycopg2-binary pandas

"""Establishing Connection




"""

from sqlalchemy import create_engine, text
import pandas as pd

DATABASE_URL = "postgresql+psycopg2://neondb_owner:npg_gKZA34qbpwcn@ep-silent-flower-ahlxmd8q.c-3.us-east-1.aws.neon.tech/demodb?sslmode=require&channel_binding=require"

engine = create_engine(DATABASE_URL)

with engine.connect() as conn:
    print(conn.execute(text("SELECT now()")).fetchone())



   # postgresql://neondb_owner:npg_gKZA34qbpwcn@ep-silent-flower-ahlxmd8q.c-3.us-east-1.aws.neon.tech/demodb?sslmode=require&channel_binding=require

# from sqlalchemy import create_engine, text
# import pandas as pd

# DATABASE_URL = (
#     "postgresql+psycopg2://neondb_owner:npg_gKZA34qbpwcn@"
#     "ep-rough-silence-ah0q7j5r.c-3.us-east-1.aws.neon.tech/"
#     "demodb?sslmode=require&channel_binding=require"
# )

# engine = create_engine(DATABASE_URL)

# with engine.connect() as conn:
#     result = conn.execute(text("SELECT now()"))
#     print(result.fetchone())

table_name = "customer"   # <-- change this

data.to_sql(
    name=table_name,
    con=engine,
    if_exists="append",   # append = insert new rows
    index=False
)

print("✅ Data inserted successfully!")



